import 'jest-extended';
import request from 'supertest';
import uuidv4 from 'uuidv4';
import app from '../app';
import {setupDummyData, userOne, AuthToken1,AuthToken3, clearDummyData} from './fixtures/TestData';
import {SetupDummyDatabase,article1,article5,article3,comment1,comment2 } from './fixtures/ArticleData';
import ArticleModal from '../modals/ArticleModal';

beforeAll(setupDummyData);
beforeAll(SetupDummyDatabase);


test('Should create a new article for a valid user ', async () => {
    await request(app).post('/articles')
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send({
            title: 'Dummy title',
            content: 'This is dummy data generated by jest'
        }).expect(200);
});

test('Should not create article for invalid user', async () => {
    await request(app).post('/articles')
    .set('Authorization', `Bearer ${AuthToken3}`)
    .send({
        title: 'Dummy Title',
        content: 'Dummy content'
    }).expect(404)
});

test('Should not create article with no title', async () => {
    await request(app).post('/articles')
    .set('Authorization', `Bearer ${AuthToken3}`)
    .send({
        content: 'Dummy Content'
    }).expect(400)
});

test('Should not create article with no content/body', async () => {
    await request(app).post('/articles')
    .set('Authorization',`Bearer ${AuthToken1}`)
    .send({
        content:'Dummy Data'
    }).expect(400)
});

test('Should show all articles in a sorted manner', async () => {
    await request(app)
        .get('/feeds')
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send()
        .expect(200)
});

test('Should not show articles if user is not logged in', async () => {
    await request(app)
        .get('/feeds')
        .send()
        .expect(401)
});

test('should return articles for the current user', async() => {
    const resp = await request(app)
        .get('/feed/me')
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send()
        .expect(200)
});

test('Should not return nothing for user with no articles', async () => {
    const resp = await request(app)
        .get('/feed/me')
        .set('Authorization', `Bearer ${AuthToken3}`)
        .send()
        .expect(404)
})

test('should not return articles for unregistered user', async() => {
    await request(app)
        .get('/feed/me')
        .send()
        .expect(401)
});
test('should not show articles for user with no articles', async() => {
    await request(app)
        .get('/feed/me')
        .set('Authorization', `Bearer ${AuthToken3}`)
        .send()
        .expect(404)
});
test('Should not delete non existent article', async () => {
    await request(app)
        .delete(`/articles/${article3.article_id}`)
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send()
        .expect(404)
});

test('Should delete an article', async () => {
    const myArticle = {
            title: 'This is manuall title',
            content: 'This is a manual body',
            createdBy: userOne.email,
    };
    const saveArticle = ArticleModal.saveArticle(myArticle);
    await request(app)
    .delete(`/articles/${saveArticle.article_id}`)
    .set('Authorization', `Bearer ${AuthToken1}`)
    .send()
    .expect(200)
});

test('should update an article', async () => {
    const myArticle = {
        title: article1.title,
        article: article1.content
    };
    const saveArticle = ArticleModal.saveArticle(myArticle);
    await request(app)
        .patch(`/articles/${saveArticle.article_id}`)
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send({
            title: "This is a custom title"
        })
        .expect(200)
});

test('Should not update non existent article', async () => {
    const random_id = uuidv4();
    await request(app)
        .patch(`/articles/${random_id}`)
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send({title: 'Random title'})
        .expect(404)
});

test('Should create a comment for a registered user', async() => {
    const myArticel = {
        title: "Dummy data 1",
        content: "Dummy data 2",
        email:  userOne.email
    }
    const saveArticle = ArticleModal.saveArticle(myArticel);
    await request(app)
        .post(`/articles/${saveArticle.article_id}/comments`)
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send({comment: "This dummy cmmonent"})
        .expect(201)
});

test('Should not create a comment for non existent article', async () => {
    const fakeArticleId = uuidv4();
    await request(app)
        .post(`/articles/${fakeArticleId}/comments`)
        .set('Authorization', `Bearer ${AuthToken1}`)
        .send({comment: "Another dummy comment"})
        .expect(404)
});

test('should not create a comment with no body', async () => {
    const myArticel = {
        title: "Dummy data 1",
        content: "Dummy data 2",
        email:  userOne.email
    }
    const saveArticle = ArticleModal.saveArticle(myArticel);
    await request(app)
    .post(`/articles/${saveArticle.article_id}/comments`)
    .set('Authorization', `Bearer ${AuthToken1}`)
    .send()
    .expect(400)
})
