sudo: false
language: node_js
node_js:
  - "11.15.0"
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run test
after_success:
  - npm run coverage